# Generated by Django 5.2.3 on 2025-06-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_property_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.AddField(
            model_name='property',
            name='id_property',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
