# Generated by Django 5.2.3 on 2025-06-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_property_id_property_id_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='id_property',
            new_name='idProperty',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='type_property',
            new_name='typeProperty',
        ),
    ]
