# Generated by Django 5.2.3 on 2025-06-21 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_id_property_property_idproperty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='idProperty',
            new_name='id_property',
        ),
    ]
