# Generated by Django 5.2.3 on 2025-06-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_idproperty_property_id_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='descripion',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
