# Generated by Django 5.2.3 on 2025-06-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property_descripion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='descripion',
            new_name='description',
        ),
    ]
